spring.application.name=revieworder


spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DB 초기화 전략
spring.jpa.hibernate.ddl-auto:none


springdoc.swagger-ui.path=/swagger-ui.html